# Generated by Django 5.0.6 on 2024-11-10 11:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_info', models.TextField(blank=True, max_length=150, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=11, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number.', regex='^\\+92[3-9][0-9]{9}$|^(0[3-9]{1}[0-9]{2})[ -]?[0-9]{7}$')])),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': 'Contact',
            },
        ),
    ]
