# Generated by Django 5.0.6 on 2024-11-09 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=10, null=True)),
                ('last_name', models.CharField(blank=True, max_length=10, null=True)),
                ('photo', models.FileField(blank=True, max_length=200, null=True, upload_to='Profile_photo')),
                ('profession_1', models.CharField(blank=True, max_length=20, null=True)),
                ('profession_2', models.CharField(blank=True, max_length=20, null=True)),
                ('profession_3', models.CharField(blank=True, max_length=20, null=True)),
                ('twitter_link', models.CharField(blank=True, max_length=300, null=True)),
                ('facebook_link', models.CharField(blank=True, max_length=300, null=True)),
                ('linkedin_link', models.CharField(blank=True, max_length=300, null=True)),
                ('github_link', models.CharField(blank=True, max_length=300, null=True)),
                ('instagram_link', models.CharField(blank=True, max_length=300, null=True)),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': 'Home Page',
            },
        ),
    ]
