# Generated by Django 5.0.6 on 2024-11-09 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='page_title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
