# Generated by Django 5.0.6 on 2024-11-10 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_home_page_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='nav_logo',
            field=models.FileField(blank=True, max_length=200, null=True, upload_to='Nav_Logo/'),
        ),
    ]
