# Generated by Django 5.0.6 on 2024-11-15 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_alter_home_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='photo',
            field=models.FileField(max_length=200, null=True, upload_to='Profile_photo'),
        ),
    ]
