# Generated by Django 6.0.3 on 2026-03-13 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0006_alter_home_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='home',
            name='facebook_link',
        ),
        migrations.RemoveField(
            model_name='home',
            name='instagram_link',
        ),
        migrations.RemoveField(
            model_name='home',
            name='twitter_link',
        ),
    ]
