# Generated by Django 5.0.6 on 2024-11-09 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('About', '0002_about_cv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='introduction',
            field=models.TextField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='about',
            name='introduction_description',
            field=models.TextField(blank=True, max_length=400, null=True),
        ),
    ]
