# Generated by Django 5.0.6 on 2024-11-15 12:36

import About.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('About', '0006_alter_about_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='cv',
            field=models.FileField(null=True, upload_to='CV/', validators=[About.models.validate_pdf]),
        ),
        migrations.AlterField(
            model_name='about',
            name='photo',
            field=models.FileField(max_length=200, null=True, upload_to='Profile_photo'),
        ),
    ]
