# Generated by Django 5.0.6 on 2024-11-10 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, max_length=30, null=True)),
                ('image', models.FileField(blank=True, max_length=200, null=True, upload_to='Portfolio')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': 'Portfolio',
            },
        ),
    ]
