# Generated by Django 5.0.6 on 2024-11-10 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0002_category_portfolio_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='Portfolio', to='Portfolio.category'),
        ),
    ]
