# Generated by Django 5.0.6 on 2024-11-10 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0003_alter_portfolio_categories'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': '', 'verbose_name_plural': 'Categoris'},
        ),
    ]
