# Generated by Django 5.0.6 on 2024-11-10 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0004_alter_category_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': '', 'verbose_name_plural': 'Categories'},
        ),
    ]
