# Generated by Django 5.0.6 on 2024-11-10 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0005_alter_category_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='categories',
            field=models.ManyToManyField(to='Portfolio.category'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='image',
            field=models.FileField(blank=True, max_length=200, null=True, upload_to='Portfolio/'),
        ),
    ]
