# Generated by Django 6.0.3 on 2026-03-13 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0006_alter_portfolio_categories_alter_portfolio_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
