# Generated by Django 5.0.6 on 2024-11-09 20:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Skills', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skills',
            old_name='skill_name',
            new_name='left_side_skill_name',
        ),
        migrations.RemoveField(
            model_name='skills',
            name='skill_percentage',
        ),
        migrations.AddField(
            model_name='skills',
            name='left_side_skill_percentage',
            field=models.PositiveSmallIntegerField(null=True, validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='skills',
            name='right_side_skill_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='skills',
            name='right_side_skill_percentage',
            field=models.PositiveSmallIntegerField(null=True, validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
