# Generated by Django 5.0.6 on 2024-11-10 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Skills', '0004_alter_skills_skill_1_percentage_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skills',
            old_name='skill_1_name',
            new_name='left_skill_name',
        ),
        migrations.RenameField(
            model_name='skills',
            old_name='skill_1_percentage',
            new_name='left_skill_percentage',
        ),
        migrations.RenameField(
            model_name='skills',
            old_name='skill_2_name',
            new_name='right_skill_name',
        ),
        migrations.RenameField(
            model_name='skills',
            old_name='skill_2_percentage',
            new_name='right_skill_percentage',
        ),
        migrations.RemoveField(
            model_name='skills',
            name='skill_3_name',
        ),
        migrations.RemoveField(
            model_name='skills',
            name='skill_3_percentage',
        ),
        migrations.RemoveField(
            model_name='skills',
            name='skill_4_name',
        ),
        migrations.RemoveField(
            model_name='skills',
            name='skill_4_percentage',
        ),
        migrations.RemoveField(
            model_name='skills',
            name='skill_5_name',
        ),
        migrations.RemoveField(
            model_name='skills',
            name='skill_5_percentage',
        ),
        migrations.RemoveField(
            model_name='skills',
            name='skill_6_name',
        ),
        migrations.RemoveField(
            model_name='skills',
            name='skill_6_percentage',
        ),
    ]
