# Generated by Django 5.0.6 on 2024-11-10 08:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Skills', '0005_rename_skill_1_name_skills_left_skill_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skills',
            old_name='left_skill_name',
            new_name='skill_1_name',
        ),
        migrations.RenameField(
            model_name='skills',
            old_name='left_skill_percentage',
            new_name='skill_1_percentage',
        ),
        migrations.RenameField(
            model_name='skills',
            old_name='right_skill_name',
            new_name='skill_2_name',
        ),
        migrations.RenameField(
            model_name='skills',
            old_name='right_skill_percentage',
            new_name='skill_2_percentage',
        ),
        migrations.AddField(
            model_name='skills',
            name='skill_3_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='skills',
            name='skill_3_percentage',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='skills',
            name='skill_4_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='skills',
            name='skill_4_percentage',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='skills',
            name='skill_5_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='skills',
            name='skill_5_percentage',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='skills',
            name='skill_6_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='skills',
            name='skill_6_percentage',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
