# Generated by Django 5.0.6 on 2024-11-10 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resume', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resume',
            old_name='description',
            new_name='education_description',
        ),
        migrations.RenameField(
            model_name='resume',
            old_name='title',
            new_name='education_title',
        ),
        migrations.RenameField(
            model_name='resume',
            old_name='title_details',
            new_name='education_title_details',
        ),
        migrations.AddField(
            model_name='resume',
            name='experience_description',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='experience_title',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='experience_title_details',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
    ]
