# Generated by Django 5.0.6 on 2024-11-10 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resume', '0002_rename_description_resume_education_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='education_title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='education_title_details',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='experience_title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='experience_title_details',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
